# @package _group_
# new town / train weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town02
    routes_group: null
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town04
    routes_group: test
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town05
    routes_group: null
    weather_group: train_eval