# @package _group_
# train town / train weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town01
    routes_group: null
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town03
    routes_group: null
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town04
    routes_group: train
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town06
    routes_group: null
    weather_group: train_eval
# train town / new weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town01
    routes_group: null
    weather_group: new
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town03
    routes_group: null
    weather_group: new
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town04
    routes_group: train
    weather_group: new
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town06
    routes_group: null
    weather_group: new
# new town / train weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town02
    routes_group: null
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town04
    routes_group: test
    weather_group: train_eval
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town05
    routes_group: null
    weather_group: train_eval
# new town / new weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town02
    routes_group: null
    weather_group: new
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town04
    routes_group: test
    weather_group: new
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town05
    routes_group: null
    weather_group: new