# @package _group_
- env_id: Endless-v0
  env_configs:
    carla_map: Town02
    num_zombie_vehicles: [0, 100]
    num_zombie_walkers: [0, 200]
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town03
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 150]
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town04
    num_zombie_vehicles: [0, 200]
    num_zombie_walkers: [0, 200]
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 200]
    num_zombie_walkers: [0, 200]
  gpu: [0]
