# @package _group_
- env_id: Endless-v0
  env_configs:
    carla_map: Town01
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town01
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [1]
- env_id: Endless-v0
  env_configs:
    carla_map: Town02
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town02
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [1]
- env_id: Endless-v0
  env_configs:
    carla_map: Town03
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town03
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [1]
- env_id: Endless-v0
  env_configs:
    carla_map: Town04
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town04
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [1]
- env_id: Endless-v0
  env_configs:
    carla_map: Town05
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town05
    num_zombie_vehicles: [0, 150]
    num_zombie_walkers: [0, 300]
    weather_group: dynamic_1.0
  gpu: [1]
