# @package _group_
entry_point: agents.cilrs.models.trainer:Trainer
kwargs:
  batch_size: 64
  num_workers: 4
  learning_rate: 0.0002
  lr_schedule_factor: 0.5
  branch_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  action_weights: [0.5, 0.5]
  speed_weight: 0.05
  value_weight: 0.0
  features_weight: 0.0
  l1_loss: true
  action_kl: true
  action_agg: null
  action_mll: null
  starting_iteration: 0
  starting_epoch: 0
  im_augmentation: 'hard'