# @package _group_
birdview:
  module: birdview.chauffeurnet
  width_in_pixels: 192
  pixels_ev_to_bottom: 40
  pixels_per_meter: 5.0
  history_idx: [-16, -11, -6, -1]
  scale_bbox: false
  scale_mask_col: 1.1
speed:
  module: actor_state.speed
control:
  module: actor_state.control
velocity:
  module: actor_state.velocity