actors:
  hero:
    agent: ppo
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
carla_sh_path: /home/ubuntu/apps/carla/carla910/CarlaUE4.sh
curriculum: false
defaults:
- agent: ppo
- agent/ppo/policy: xtma_beta
- agent/ppo/training: ppo
- agent/ppo/obs_configs: birdview
- train_envs: endless_all
dummy: false
ev_id: hero
kill_running: true
seed: 2021
total_timesteps: 2691072
wb_name: null
wb_notes: null
wb_project: train_rl
wb_tags: null
