# @package _group_
ppo:
  entry_point: agents.rl_birdview.rl_birdview_agent:RlBirdviewAgent
  wb_run_path: null
  wb_ckpt_step: null
  env_wrapper:
    entry_point: agents.rl_birdview.utils.rl_birdview_wrapper:RlBirdviewWrapper
    kwargs:
      input_states: [control, vel_xy]
      acc_as_action: True